# Site settings
title: Summer School in Geometric Representation Theory
short-title: SSGRT
subtitle: IST Vienna
#email: youremailaddress@gmail.com
description: A workshop and conference at IST Vienna
#baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: IST Austria, Am Campus 1,
city: 3400 Klosterneuburg
#state: 
#zip_code: 55555
country: Austria
#phone: (716) 555-5555

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# Build settings
markdown: kramdown

sass:
  style: compressed
